### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by jernejp21** [jernejp21/Marlin#1]
- [ ] Configuration.h:1097 `#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 400, 93 }`
- [ ] Configuration.h:1104 `#define DEFAULT_MAX_FEEDRATE          { 500, 500, 5, 25 }`
- [ ] Configuration.h:1117 `#define DEFAULT_MAX_ACCELERATION      { 500, 500, 100, 5000 }`
- [ ] Configuration.h:1132 `#define DEFAULT_ACCELERATION           500`
- [ ] Configuration.h:1200 `#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN`
- [ ] Configuration.h:1388 `#define NOZZLE_TO_PROBE_OFFSET { -38, -8, 0 }`
- [ ] Configuration.h:1448 `#define MULTIPLE_PROBING 2`
- [ ] Configuration.h:1587 `#define X_BED_SIZE 300`
- [ ] Configuration.h:1652 `#define FILAMENT_RUNOUT_SENSOR`
- [ ] Configuration.h:1821 `#define GRID_MAX_POINTS_X 5`
- [ ] Configuration.h:1894 `#define LCD_BED_TRAMMING`
- [ ] Configuration.h:1963 `#define HOMING_FEEDRATE_MM_M { (40*60), (40*60), (6*60) }`
- [ ] Configuration.h:2074 `#define PREHEAT_1_LABEL       "PLA"`
- [ ] Configuration.h:3111 `#define NEOPIXEL_TYPE          NEO_GRBW`
- [ ] Configuration_adv.h:502 `#define USE_CONTROLLER_FAN`
- [ ] Configuration_adv.h:839 `#define HOMING_BUMP_MM      { 0, 0, 2 }`
- [ ] Configuration_adv.h:1633 `#define SDCARD_CONNECTION ONBOARD`
- [ ] Configuration_adv.h:2009 `#define LIN_ADVANCE`
- [ ] Configuration_adv.h:2558 `#define FILAMENT_LOAD_UNLOAD_GCODES`
- [ ] Configuration_adv.h:2717 `#define X_CURRENT`
- [ ] Configuration_adv.h:3093 `#define SENSORLESS_HOMING`
